/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113114-gc1340f3439-20231228"
#endif /* AVUTIL_FFVERSION_H */
