# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build application

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw32 }
          - { sys: mingw64 }
          - { sys: ucrt64  }
          - { sys: clang64 }
    name: ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: 'Setup MSYS2 (${{ matrix.sys }})'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          qt6-base:p

    - name: 'Build application'
      run: |
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
